### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [antoshka77/engCheckers#1]
Слишком похоже на [эти шашки](https://github.com/bdhadley/Checkers). Ваших изменений явно не хватает по сложности для курсового проекта.

**Comment by antoshka77** [comment]
Кирилл Алексеевич, какие ещё изменения нужно внести, что добавить, чтобы все было нормально?

**Comment by gagarski** [comment]
Выдано другое задание, эта issue закрыта.
